### ISSUE TITLE
Streamable validation stylesheet

### ISSUE THREAD

**Issue by dmj** [schxslt/schxslt#146]
The validation stylesheet should be constructed in a way that allows for streaming. The challenges:

- [ ] schxslt:location uses position() which is not allowed when streaming
- [x] pattern/@documents

**Comment by yamahito** [comment]
How about using xsl:accumulator?  And is fn:path streamable?

**Comment by dmj** [comment]
fn:path is sadly not streamable. Judging from @martin-honnen's code providing an equivalent using accumulators is not that easys.

**Comment by yamahito** [comment]
(for posterity, here's @martin-honnen 's code: https://github.com/martin-honnen/schxslt/blob/release-1.4.6-xslt3-streaming-test/src/main/resources/xslt/3.0-streamable/streaming-utilities/position-accumulator.xsl )

**Comment by michaelhkay** [comment]
At one time during XSLT 3.0 development, we considered maintaining the sibling position (count of previous siblings) of a node as part of the data associated with a node. But there turned out to be too many variations wanted, e.g. number of siblings of each node kind and name. And the value of position() of course isn't a property of the node, it's a property of how you got there. A library providing streamable position information (or even path()) via accumulators seems the right way to do it. Note also, Saxon provides saxon:line-number() for streamable nodes. But let's take a step back: if you've got 30Gb of input and you're told there's an invalidity half way through it, what are you actually going to do about it? Because the only purpose of position information is to enable you to correct the data, or discover why it's wrong.

**Comment by dmj** [comment]
I will move towards a streamable validation template with the upcoming version 1.6 as follows:

- if the query binding ist xslt3, then processing the pattern/@‍documents attribute that reads external documents is implemented using &lt;source-document&gt;
- if the query binding ist xslt3 and the compiler stylesheet is called with the parameter ```schxslt.compile.streamable``` set to boolean true, then all modes in the generated stylesheet are declared as @‍streamable="yes"

It is up to the user to provide an appropriate and streamable ```schxslt:location``` function.
