### ISSUE TITLE
Does Schematron support built-in namespaces, such as "xs:"?

### ISSUE THREAD

**Issue by GerbenAbbink** [schxslt/schxslt#332]
I was wondering: Is XSD a built-in namespace in Schematron, or do I always have to use ns if I want to use prefix "xs"?

For example

```
<?xml version="1.0" encoding="UTF-8"?>
<sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt" schemaVersion="3.1.2">
        <!-- IS THIS MANDATORY? -->
	<sch:ns prefix="xs" uri="http://www.w3.org/2001/XMLSchema"/>
	<sch:pattern fpi="MedinOriginatorPointOfContact">
		<sch:rule context="/*/identificationInfo/*/xs:pointOfContact[*/role/*/@codeListValue = 'owner']">
			<sch:assert test="100">
      </sch:assert>
		</sch:rule>
	</sch:pattern>
</sch:schema>

```

**Comment by GerbenAbbink** [comment]
I did some more experiments. It seems that it changed between version 1 and 2? In version 1, the "xs" prefix is not built-in, in version 2 it is. Is this the Schematron standard, or is this a bug?

**Comment by dmj** [comment]
ISO Schematron does not have a concept of built-in namespaces. Thus you have to declare the xs: namespace in order to use it. _However_: What you experience is, that the SchXslt stylesheets bind the xs: namespace internally and don't remove it when generating the validation stylesheet. And you are right: This is could be seen as a bug. In the specifications:

> Namespace prefixes in context expressions, assertion tests and other query expressions shall be defined by this (sc. sch:ns) element. Namespace prefixes should not use the namespace bindings in scope for element and attribute names.

Given that SchXslt is a non-conforming ISO Schematron processor and already implementing things not present in the specifications I would not fix this bug here, but in the [SchXslt Redux XSLT 1.0](https://github.com/schxslt/schxslt-redux-xslt1) and [SchXslt Redux XSLT 2.0](https://github.com/schxslt/schxslt-redux-xslt2).

**Comment by GerbenAbbink** [comment]
Clear. Thank you.
